### ISSUE TITLE
Ulfius build on Mac OS X

### ISSUE THREAD

**Issue by briandowns** [babelouest/ulfius#25] opened 2017-08-02 03:48 UTC
My apologies if this is solved somewhere and I haven't found it yet but wanted to get some feedback on the error I'm currently seeing when trying to compile.  I'm trying to compile on MacOS 10.12.3. Thanks in advance!

```
➜  orcania git:(0adb944) make && sudo make install
cd ./src && /Library/Developer/CommandLineTools/usr/bin/make debug
gcc -shared -Wl,-soname,liborcania.so -o liborcania.so.1.1 orcania.o memory.o base64.o -lc -ljansson
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [liborcania.so] Error 1
make: *** [debug] Error 2
```

**Comment by babelouest** [comment] 2017-08-02 10:02
So far I think you're the first one telling me you're trying to build ulfius on macosx, thanks for the feedback.
By googling it, I see that you have to replace the keyword `soname` with `install_name` in the Makefile, like in https://github.com/hoedown/hoedown/issues/167
Can you try this change with the Makefile in `lib/orcania/src`, `lib/yder/src` and `src` and tell me if the build succeed?
I don't have a Mac to test the build on this architecture, your help would be appreciated!

**Comment by briandowns** [comment] 2017-08-02 16:43
Thanks for the fast reply! I googled as well but fell short. Changing that worked to get orcania installed, errors on ldconfig, then when compiling yder, it's unable to find orcania. Then again, there's no ldconfig on Mac. Gonna continue googling but I'll take any suggestions. Thanks!

**Comment by babelouest** [comment] 2017-08-02 18:56
Thanks, Indeed there seem to be no `ldconfig` command in OS X.

Basically, the OS X build procedure is different enough to require its own Makefile command.

In fact, the `Makefile` is linux specific for now. I would gladly have a platform agnostic installer like autotool/autoconf but so far I'm not able to generate proper `config.ac` or `Makefile.am` files.

I can see that to build a dynamic library for OS X, the result file is named `*.dylib`:
https://stackoverflow.com/questions/3532589/how-to-build-a-dylib-from-several-o-in-mac-os-x-using-gcc

And it seems that there is no need to reload the library cache, so no `ldconfig`:
https://discussions.apple.com/thread/3844649?tstart=0

But the `install_name` option seems important in OS X build:
http://log.zyxar.com/blog/2012/03/10/install-name-on-os-x/

A working compile command of orcania may look like this:
```shell
cd orcania/src
gcc -c -fPIC -Wall -D_REENTRANT -O3 orcania.c
gcc -c -fPIC -Wall -D_REENTRANT -O3 memory.c
gcc -c -fPIC -Wall -D_REENTRANT -O3 base64.c
gcc -dynamiclib -current_version 1.1 orcania.o memory.o base64.o -o liborcania.dylib -install_name ${PREFIX}/lib/liborcania.dylib
```

Then compile yder with similar commands. Since orcania is a dependency of yder, if orcania is correctly built and installed, yder should compile too.
```shell
cd yder/src
gcc -c -fPIC -Wall -D_REENTRANT -O3 yder.c
gcc -dynamiclib -current_version 2.0 yder.o -o libyder.dylib -lorcania -install_name ${PREFIX}/lib/libyder.dylib
```

Then finally, build ulfius with similar commands as well.

Let me know how it goes, I'll do my best to help you!

**Comment by dariota** [comment] 2017-08-20 11:29
@briandowns I had a similar issue with yder not finding orcania when installing on Arch Linux - I ran `ld -lorcania --verbose` to find out where it was looking for orcania and realised it wasn't handling the version number. I suspect handling the versioning isn't supported for me since Arch is a rolling release distro unlike debian.

In any case, the solution for me (I didn't change PREFIX, so you may need to change the commands a bit if you did) was to symlink the unversioned name to a versioned one, like so `ln -s /usr/local/lib/liborcania.so.1.1 /usr/local/lib/liborcania.so`. You'll have to do the same with ulfius itself, and probably with yder as well (I haven't actually built a test project yet).

@babelouest My suggestion to fix this would be to have the makefile for yder, orcania and ulfius create those symlinks. I can put those PRs in for you if you like?

**Comment by babelouest** [comment] 2017-08-20 19:48
@briandowns , I don't think that's related to this topic.

The issue here is to build ulfius on a MacOS X platform, and it looks like linux standard commands like `ld*` and compiler linking is not the same. In fact, the target file doesn't even have the same name and pattern. It's a `dylib` file instead of a `so` file.

But you make me wonder how you have your problems with Arch Linux. In the `Makefile, inn the install process, there is a `ln -s` command to make a symlink. This should work as long as you have write access to the PREFIX directory. Can you open another issue so you can describe your problem and we can figure out how to make a clean install on Arch Linux?

**Comment by dariota** [comment] 2017-08-20 21:17
I was referring specifically on that topic to the comment

>  then when compiling yder, it's unable to find orcania

as that's the same issue that I was having due to the version numbers.

Also, looking at the Makefile, there is no `ln` that would solve this issue, but that can be discussed in a new issue.

**Comment by babelouest** [comment] 2017-08-21 13:55
No problem, although I'm still curious about your `failure in running ldconfig` and how you fixed it or found workaround.
Since #26 , the ldconfig command is harmless if it fails. Can you retry an install on Arch with an up to date version of ulfius?

**Comment by dariota** [comment] 2017-08-21 14:09
I can't recall exactly what I did to cause the setup to fail - maybe ran
`make install` rather than `sudo make install`. It seems `ldconfig` was
setting up a symlink from `/usr/local/lib/liborcania.so` to
`/usr/local/lib/liborcania.so.1.1`, so when `ldconfig` failed to run due
to lack of root privileges, `ld` couldn't find orcania since it was
specifically looking for `/usr/local/lib/liborcania.so`, without the
version number.

When retrying an install, correctly running `make install` with root
privileges, everything worked perfectly fine.

Kind regards,
Dário Tavares Antunes

**Comment by JohnB33** [comment] 2018-01-20 20:34
I'm on Yosemite 10.10.5 and I've compiled the two libraries and copied them to /usr/local/lib.
I've compiled everything in ulfius/src apart from u_websocket.c. 

Any help with proceeding would be appreciated. BTW I have it working on a RaspberryPi and it's awesome. 

Thanks J.

$ gcc -c -fPIC -Wall -D_REENTRANT -O3 u_websocket.c 
u_websocket.c:115:44: error: use of undeclared identifier 'PTHREAD_MUTEX_RECURSIVE_NP'
    pthread_mutexattr_settype( &mutexattr, PTHREAD_MUTEX_RECURSIVE_NP );
                                           ^
u_websocket.c:610:47: error: use of undeclared identifier 'MSG_NOSIGNAL'
      ret = send(sock, &data[off], len - off, MSG_NOSIGNAL);

**Comment by babelouest** [comment] 2018-01-20 21:10
You may be in luck, I made a push this week to fix the `PTHREAD_MUTEX_RECURSIVE_NP` issue.

Maybe I have a spider sense for bugs, who knows?
Actually I don't have spider sense, I just had a similar big when I built ulfius on alpine Linux ;)

Still, can you `git pull` the last version of ulfius or download the last release and check if this problem has disappeared?

And if you don't mind, if you succeed building ulfius on macosx, can you explain the procedure so I can update the documentation?

**Comment by JohnB33** [comment] 2018-01-20 21:27
Hi, Must have been tingling big time :-)

Sorry I've got bad news for you. It's not working :-(

$ cd src
$ make
gcc -c -pedantic -std=gnu99 -fPIC -Wall -D_REENTRANT -I/usr/local/include -I../lib/orcania/src -I../lib/yder/src -O3    u_websocket.c
In file included from u_websocket.c:26:
./u_private.h:169:26: warning: no newline at end of file [-Wnewline-eof]
#endif // __U_PRIVATE_H__
                         ^
u_websocket.c:609:47: error: use of undeclared identifier 'MSG_NOSIGNAL'
      ret = send(sock, &data[off], len - off, MSG_NOSIGNAL);

**Comment by babelouest** [comment] 2018-01-20 21:43
I'll fix the warning in a future commit.

For the `MSG_NOSIGNAL`, unless you need to use the websockets, can you try an build Ulfius without them?

```shell
$ make WEBSOCKETFLAG=-DU_DISABLE_WEBSOCKET
```

**Comment by JohnB33** [comment] 2018-01-21 16:07
Sorry to spam you, I'm trying to make sure you've got all the info you need. I did had another look and discovered the orcadia and yder directories were empty. So I deleted the directory and did another git clone, which sorted that issue out.

I found I could manually compile orcada and yder if I copied the lib to /usr/local/lib so that the yder compile could see it. Make for neither of them worked without replacing soname with install_name.

I replaced soname in all three Makefiles and here's the result of the make (read to the bottom please).

make WEBSOCKETFLAG=-DU_DISABLE_WEBSOCKET
cd ./src && /Applications/Xcode.app/Contents/Developer/usr/bin/make   
gcc -shared -Wl,-install_name,libulfius.so -o libulfius.so.2.2.4 ulfius.o u_map.o u_request.o u_response.o u_send_request.o u_websocket.o -L/usr/local/lib -L../lib/orcania/src -L../lib/yder/src -lc -lmicrohttpd -lyder -lorcania -lpthread -ljansson -lcurl 
Undefined symbols for architecture x86_64:
  "_ulfius_check_list_match", referenced from:
      _ulfius_webservice_dispatcher in ulfius.o
  "_ulfius_generate_handshake_answer", referenced from:
      _ulfius_webservice_dispatcher in ulfius.o
  "_ulfius_instance_add_websocket_active", referenced from:
      _ulfius_webservice_dispatcher in ulfius.o
  "_ulfius_start_websocket_cb", referenced from:
      _ulfius_webservice_dispatcher in ulfius.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libulfius.so] Error 1
make: *** [libulfius.so] Error 2

Then I did a make clean. Then make WEBSOCKETFLAG=-DU_DISABLE_WEBSOCKET
There were the usual warnings about no newlines, but it worked Spidey :-)

**Comment by babelouest** [comment] 2018-01-21 18:19
This is awesome news!

Instead of trying to update the Makefile for MacOSX, I think I will try for the CMake script to be ready. As I understand it, it will make Ulfius available on other platforms, Windows and OSX at least.
The fact that you were able to build it by hand is very promising though, so hopefully there won't be too much change in the code.

In the mean time, I will try to fix the `MSG_NOSIGNAL` problem, so even OSX will have the power of websockets!
https://nwat.xyz/blog/2014/01/16/porting-msg_more-and-msg_nosigpipe-to-osx/

**Comment by briandowns** [comment] 2018-02-18 03:30
I can take a look this evening or tomorrow. Thanks!

**Comment by JohnB33** [comment] 2018-02-19 08:35
Hi I did a complete rebuild on my Mac as I upgraded to an SSD, so I'm trying from scratch. I have a missing microhttpd.h error on make. I seem to remember I had issues installing libmicrohttpd-dev before. I'll let you know when I make progress.

**Comment by JohnB33** [comment] 2018-02-19 20:00
The MSG_NOSIGNAL problem is back :-(  Unless I've done something stupid.

make WEBSOCKETFLAG=-DU_DISABLE_WEBSOCKET && sudo make install
[  7%] Building C object orcania-build/CMakeFiles/orcania.dir/src/base64.c.o
[ 15%] Building C object orcania-build/CMakeFiles/orcania.dir/src/memory.c.o
[ 23%] Building C object orcania-build/CMakeFiles/orcania.dir/src/orcania.c.o
[ 30%] Linking C shared library liborcania.dylib
[ 30%] Built target orcania
[ 38%] Building C object yder-build/CMakeFiles/yder.dir/src/yder.c.o
[ 46%] Linking C shared library libyder.dylib
[ 46%] Built target yder
[ 53%] Building C object CMakeFiles/ulfius.dir/src/u_map.c.o
[ 61%] Building C object CMakeFiles/ulfius.dir/src/u_request.c.o
[ 69%] Building C object CMakeFiles/ulfius.dir/src/u_response.c.o
[ 76%] Building C object CMakeFiles/ulfius.dir/src/u_send_request.c.o
[ 84%] Building C object CMakeFiles/ulfius.dir/src/u_websocket.c.o
/Users/johnboyer/work/ulfius/src/u_websocket.c:613:47: error: use of undeclared identifier 'MSG_NOSIGNAL'
      ret = send(sock, &data[off], len - off, MSG_NOSIGNAL);
                                              ^
1 error generated.

**Comment by babelouest** [comment] 2018-02-19 21:02
The CMake installation is a little bit different, to build Ulfius without Websocket support, you must run the following commands:

```shell
$ cd ulfius
$ mkdir build
$ cd build
$ cmake -DWITH_WEBSOCKET=off ..
$ make
$ make install # as admin
```

**Comment by briandowns** [comment] 2018-02-20 03:31
I can confirm the successful building and running on MacOS. This is awesome.

**Comment by briandowns** [comment] 2018-02-20 03:43
Trying on FreeBSD now.

**Comment by briandowns** [comment] 2018-02-20 13:54
Compiled and installed on FreeBSD. It's looking for headers in `/usr/include` when they've been installed to `/usr/local/include`. Not a big deal. I've updated that but `cc` isn't able to find `ulfius.h` even if I give the `-I` argument. Gonna work through it more today.

**Comment by babelouest** [comment] 2018-02-20 14:44
You can specify the target directory in the cmake command like this:

```shell
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
```

You can also add `/usr/local/include` with the `-I` argument as you said.

Another solution I can think of is to add `/usr/local/include` in the include path, something like:

```shell
$ export C_INCLUDE_PATH=/usr/local/include/:${C_INCLUDE_PATH}
```
(I haven't tested any of this though, I just googled it)

**Comment by briandowns** [comment] 2018-02-20 15:21
Thanks! Those are the things I'm gonna try actually. Nice to know I'm going in the correct direction.

**Comment by briandowns** [comment] 2018-02-20 15:33
I went with `cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..` and it's up and running on FreeBSD!  Thank you so much for the work to get this going.

**Comment by babelouest** [comment] 2018-02-20 18:57
This is pretty awesome!
@JohnB33 , do you confirm the build works if you disable websockets as mentionned above?

**Comment by JohnB33** [comment] 2018-02-21 07:19
Hi, Yes it I agree it is awesome. I can confirm the install works without websockets. The only problem I have is I've forgotten how to compile and example program. I did try make and got the soname error. I'm not sure the best way to proceed.

**Comment by babelouest** [comment] 2018-02-21 12:43
you also have a `CMake` script on the `example_program` directory, you can follow the [README.md](https://github.com/babelouest/ulfius/tree/master/example_programs) to build the example programs.

Ulfius must be installed before though.

**Comment by JohnB33** [comment] 2018-02-22 19:58
I can confirm that works absolutely perfectly. Sorry for not reading the instructions. Well done.

**Comment by babelouest** [comment] 2018-02-22 20:45
Very cool!

I'm closing this issue now then, feel free to reopen a new one if you see new issues on the build.

**Closed by babelouest** 2018-02-22 20:45 UTC
Labels: enhancement, help wanted

**Comment by briandowns** [comment] 2018-02-22 20:47
The outcome of this issues has far exceeded all expectations. Thank you very much!

**Comment by babelouest** [comment] 2018-02-23 04:11
Btw @briandowns , I didn't see your offer to add Ulfius to freebsd ports, I'd be happy to see that if you're willing to do it!
Let me know if you need help.

**Comment by briandowns** [comment] 2018-02-23 16:03
I'll see if I can take care of it over the next couple of weeks. I'll let you know if I need a hand. Thanks!

**Comment by fraserprice** [comment] 2018-07-19 20:54
Hi @babelouest I'm trying to set up on OSX and having some difficulties installing `orcania` (and `yder` too therefore). I have the following error:

```
> sudo make install
cd ./src && /Applications/Xcode.app/Contents/Developer/usr/bin/make install
cp liborcania.so.1.2.1 /usr/local/lib
cp ../include/orcania.h /usr/local/include
ldconfig
make[1]: ldconfig: No such file or directory
make[1]: [install] Error 1 (ignored)
```

@briandowns you seem to have encountered this issue with `ldconfig` too but didn't link a fix; it was quite a while ago but would you have any idea as to what to do?

Thanks 😃

**Comment by babelouest** [comment] 2018-07-19 22:07
@fraserprice , your problem is that ldconfig is not present in MacOSX.

You could tweak the `Makefile` to change the target path and other values, but I strongly suggest you try installing ulfius with the [CMake script](https://github.com/babelouest/ulfius/blob/master/INSTALL.md#cmake---multi-architecture) instead.
You need [CMake](https://cmake.org/install/) installed.

See [this comment in this thread](https://github.com/babelouest/ulfius/issues/25#issuecomment-366801963) to run cmake command on MacOSX.

If installing with CMake doesn't work, can you open a new issue then?

**Comment by davideuler** [comment] 2022-09-13 14:06
The CMake script works on Mac.  Thanks. 

```
brew install gnutls
brew install libmicrohttpd
```

Build ulfius, and download the dependencies:

```
$ git clone https://github.com/babelouest/ulfius.git
$ cd ulfius
$ mkdir build
$ cd build
$ cmake -DWITH_WEBSOCKET=off ..
```

Then if it shows error, compile and install dependencies manually:

Build orcania and install:

```
$ cd orcania-src/src
$ make
$ make install 
$ cp orcania-src/src/liborcania.so* /usr/local/lib
$ cd ..
```

Build yder and install:

``` 
$ cd yder/src 
$ make Y_DISABLE_JOURNALD=1
$ sudo make install
$ cp libyder.so* /usr/local/lib
```

Finally, change directory back to "ulfius/build", and continue to install ulfius:

```
$ cd ../
$ make
$ make install # as admin
```
