### ISSUE TITLE
How to get raw data from request?

### ISSUE THREAD

**Issue by Aventun** [babelouest/ulfius#155] opened 2020-01-22 14:36 UTC
Hi
I would like to get body raw data when a post request takes place. I have this code:

int callback_post (const struct _u_request * request, struct _u_response * response, void * user_data) 
{
	char rb[request->binary_body_length + 1];
	o_strncpy(rb, request->binary_body, request->binary_body_length);
	rb[request->binary_body_length] = '\0';
	printf("DEBUG: body data is %s \n",rb);
...

To test it:

curl -X POST -H "Content-Type: text/plain" --data "this is raw data" http://127.0.0.1:8080/api/example

But, on the server display I just see:

DEBUG: body data is

Thank you
Av

**Comment by babelouest** [comment] 2020-01-22 17:52
Hello @Aventun ,

I don't know why your code doesn't work, but if I use the following program:

```C
#include <stdio.h>
#include <ulfius.h>

#define PORT 8080

/**
 * Callback function for the web application on /api/example url call
 */
int callback_hello_world (const struct _u_request * request, struct _u_response * response, void * user_data) {
  char rb[request->binary_body_length+1];
  o_strncpy(rb, request->binary_body, request->binary_body_length);                                                                                                                                            
  rb[request->binary_body_length] = '\0';
  printf("DEBUG: body data is %s\n", rb);
  ulfius_set_string_body_response(response, 200, "Hello World!");
  return U_CALLBACK_CONTINUE;
}

/**
 * main function
 */
int main(void) {
  struct _u_instance instance;

  // Initialize instance with the port number
  if (ulfius_init_instance(&instance, PORT, NULL, NULL) != U_OK) {
    fprintf(stderr, "Error ulfius_init_instance, abort\n");
    return(1);
  }

  // Endpoint list declaration
  ulfius_add_endpoint_by_val(&instance, "POST", "/api/example", NULL, 0, &callback_hello_world, NULL);

  // Start the framework
  if (ulfius_start_framework(&instance) == U_OK) {
    printf("Start framework on port %d\n", instance.port);

    // Wait for the user to press <enter> on the console to quit the application
    getchar();
  } else {
    fprintf(stderr, "Error starting framework\n");
  }
  printf("End framework\n");

  ulfius_stop_framework(&instance);
  ulfius_clean_instance(&instance);

  return 0;
}
```

And test it with your curl command, I have the expected output on the server side.

**Comment by Aventun** [comment] 2020-01-22 18:14
The difference I see is just this one:

I am running the ulfius REST api inside a pthread...

May I?

**Comment by babelouest** [comment] 2020-01-22 18:30
Even though, I don't think running inside a pthread would change anything.

When you run `ulfius_start_framework()`, the instance is executed in a new thread and each client connections opens a new thread, so it's already multi-threaded.

In your callback function, does `request->binary_body_length` has a non-zero length?

**Comment by Aventun** [comment] 2020-01-22 19:41
Yes, size is always zero...

**Comment by babelouest** [comment] 2020-01-22 20:02
@Aventun ,

I'd need a sample code to be able to reproduce the problem then, otherwise I've got no clue...

**Comment by Aventun** [comment] 2020-01-22 20:20
I have commented all threading source code and copied / paste your sample code to the main function and ... nothing new...

**Comment by Aventun** [comment] 2020-01-22 20:29
Here his my (new) main.c (your sample code):


#include <stdio.h>
#include <ulfius.h>

#define PORT 8080

/**
 * Callback function for the web application on /api/example url call
 */
int callback_hello_world (const struct _u_request * request, struct _u_response * response, void * user_data) {
  char rb[request->binary_body_length+1];
  o_strncpy(rb, request->binary_body, request->binary_body_length);                                                                                                                                            
  rb[request->binary_body_length] = '\0';
  printf("DEBUG: body data is |%s|\n", rb);
  ulfius_set_string_body_response(response, 200, "Hello World!");
  return U_CALLBACK_CONTINUE;
}

/**
 * main function
 */
int main(void) {
  struct _u_instance instance;

  // Initialize instance with the port number
  if (ulfius_init_instance(&instance, PORT, NULL, NULL) != U_OK) {
    fprintf(stderr, "Error ulfius_init_instance, abort\n");
    return(1);
  }

  // Endpoint list declaration
  ulfius_add_endpoint_by_val(&instance, "POST", "/api/example", NULL, 0, &callback_hello_world, NULL);

  // Start the framework
  if (ulfius_start_framework(&instance) == U_OK) {
    printf("Start framework on port %d\n", instance.port);

    // Wait for the user to press <enter> on the console to quit the application
    getchar();
  } else {
    fprintf(stderr, "Error starting framework\n");
  }
  printf("End framework\n");

  ulfius_stop_framework(&instance);
  ulfius_clean_instance(&instance);

  return 0;
}


and compilation:

$gcc -o main main.c -lulfius  -lorcania -ljansson

running it and executing this in other console:
curl -X POST -H "Content-Type: text/plain" --data "this is raw data" http://127.0.0.1:8080/api/example

I see:
Start framework on port 8080
DEBUG: body data is ||

**Comment by babelouest** [comment] 2020-01-22 20:32
@Aventun you should surround code with

\```C
<your_code_here>
\```

then the code will be more readable, example:

```C
// Start the framework
if (ulfius_start_framework(&instance) == U_OK) {
printf("Start framework on port %d\n", instance.port);
```

**Comment by Aventun** [comment] 2020-01-22 21:52
```C
#include <stdio.h>
#include <ulfius.h>

#define PORT 8080

/**
 * Callback function for the web application on /api/example url call
 */
int callback_hello_world (const struct _u_request * request, struct _u_response * response, void * user_data) {
  char rb[request->binary_body_length+1];
  o_strncpy(rb, request->binary_body, request->binary_body_length);                                                                                                                                            
  rb[request->binary_body_length] = '\0';
  printf("DEBUG: body data is |%s|\n", rb);
  ulfius_set_string_body_response(response, 200, "Hello World!");
  return U_CALLBACK_CONTINUE;
}

/**
 * main function
 */
int main(void) {
  struct _u_instance instance;

  // Initialize instance with the port number
  if (ulfius_init_instance(&instance, PORT, NULL, NULL) != U_OK) {
    fprintf(stderr, "Error ulfius_init_instance, abort\n");
    return(1);
  }

  // Endpoint list declaration
  ulfius_add_endpoint_by_val(&instance, "POST", "/api/example", NULL, 0, &callback_hello_world, NULL);

  // Start the framework
  if (ulfius_start_framework(&instance) == U_OK) {
    printf("Start framework on port %d\n", instance.port);

    // Wait for the user to press <enter> on the console to quit the application
    getchar();
  } else {
    fprintf(stderr, "Error starting framework\n");
  }
  printf("End framework\n");

  ulfius_stop_framework(&instance);
  ulfius_clean_instance(&instance);

  return 0;
}
```

**Comment by babelouest** [comment] 2020-01-22 23:22
Unfortunately I can't reproduce your problem with your code:

```shell
$ ./main 
Start framework on port 8080
DEBUG: body data is |this is raw data|
```

The error seems to be somewhere else.

What OS are you using?

**Comment by Aventun** [comment] 2020-01-23 09:43
Ubuntu 19

**Comment by babelouest** [comment] 2020-01-23 13:36
I don't know what would it be.

If you run the unit tests, do they pass without error?

```shell
$ mkdir build && cd build
$ cmake -DBUILD_ULFIUS_TESTING=on ..
$ make test
```

**Comment by Aventun** [comment] 2020-01-23 15:16
Everything looks fine and these files are generated without any error:
libulfius.so.2.6
uwsc
libulfius.so  
libulfius.so.2.6.5
...

Ok, now I am going to test this on a different computer...

**Comment by Aventun** [comment] 2020-01-23 16:03
I have also reinstalled ulfius again and the problem still exists.
On a different computer also using ubuntu this sample works well. So , it seems that I need to reinstall ubuntu on my laptop :-(

Thanks for all support on this!

**Comment by babelouest** [comment] 2020-01-23 16:09
I let you close this issue then

Good luck with your reinstall!

**Closed** 2020-01-23 20:49 UTC
Labels: can't reproduce
