### ISSUE TITLE
How to implement server push?

### ISSUE THREAD

**Issue by Knutselsmurf1** [babelouest/ulfius#171] opened 2020-10-12 11:12 UTC
I want to build a server which regularly sends events to a client with a server push. 

The server controls several hardware and which should have a Rest interface. If the hardware fails, it should send an event to the client.

This is the pattern:

Server   ------------------------   Client

   <------ Connection request ------
   ------- Connection response ---->

   --------------- Event ------------->
   --------------- Event ------------->
   --------------- Event ------------->

Is this possible with Ulfius and can you give me an example.

**Comment by babelouest** [comment] 2020-10-12 12:19
Hello @Knutselsmurf1 ,

Unfortunately, it's not a matter of Ulfius, but HTTP/1.1 doesn't support push messages by design.
You have different workarounds for this though:
- Use a [websocket connection](https://github.com/babelouest/ulfius/blob/master/API.md#websockets-communication) instead of a HTTP connection. The client must implement websockets as well
- The client can call an event endpoint on the server every x seconds, to emulate a sort of server push

[HTTP/2](https://en.wikipedia.org/wiki/HTTP/2) has server push capabilities but Ulfius doesn't support HTTP/2 at the moment.

Hope that helps

Happy hacking!

**Comment by Knutselsmurf1** [comment] 2020-10-12 13:24
The websocket approach in my application is not really usable. The polling approach might be workable.

Is it expected that Ulfius gets HTTP/2 support soon? It would be nice, because it is convenient to use and its good examples. 

However do you know a possible other comparable solution for C, Linux, with HTTP/2 support and preferably json support for rather small embedded devices in the mean time?

**Comment by babelouest** [comment] 2020-10-12 13:46
> Is it expected that Ulfius gets HTTP/2 support soon?

Expected: yes
Soon: not really, depends on the definition of `soon` though

Ulfius is based on [libmicrohttpd](https://www.gnu.org/software/libmicrohttpd/), which has a work-in-progress to add HTTP/2 support, but isn't complete yet. If you want to help with the HTTP/2 support in libmicrohttpd, I'm sure they would be thrilled.

> However do you know a possible other comparable solution for C, Linux, with HTTP/2 support and preferably json support for rather small embedded devices in the mean time?

Not really, a quick search gave me some input like [this page](https://github.com/httpwg/http2-spec/wiki/Implementations), but I haven't tried any of those implementations.

**Comment by Knutselsmurf1** [comment] 2020-10-12 22:51
As an alternative, is Server Side Events supported?

**Comment by babelouest** [comment] 2020-10-12 23:22
Technically yes, but you have to implement it yourself.

Considering a Server Side Event implementation is reversing the communication flow between the http server and the client, you can switch the http service and client.

The outgoing http requests are described in the API Documentation: [Outgoing request functions ](https://github.com/babelouest/ulfius/blob/master/API.md#outgoing-request-functions)

**Comment by babelouest** [comment] 2020-10-16 21:38
@Knutselsmurf1 , does this answer your questions?

**Comment by Knutselsmurf1** [comment] 2020-10-18 22:42
> @Knutselsmurf1 , does this answer your questions?

For now I am not looking further into HTTP/2. I am not sure how I can help to build the HTTP/2 support in libmicrohttpd. If it becomes more mature I like to test it. 

I start my project with the polling approach and which is for now the most robust and easy to implement. This means that the client should call the event endpoint on the server every x seconds, to retrieve its event data. 

However for the near future I consider the Server Side Event implementation. It seems doable, however I am not sure what kind of issues could occur if I implement a reverse communication flow (for example if the connection between server and client is temporary broken, fully broken, is changed or something else). 

Thank you for helping.

**Comment by babelouest** [comment] 2020-10-18 23:54
No problem, I'm closing the issue then.

Good luck with your project!

**Closed by babelouest** 2020-10-18 23:54 UTC
Labels: question
