### ISSUE TITLE
Various Issues Cross-Compiling with MinGW and CMake

### ISSUE THREAD

**Issue by iwagner23** [babelouest/ulfius#109] opened 2019-04-12 03:54 UTC
Hello.  First, this is a great project and it has been very useful.

I've needed to cross-compile for Windows from Linux using MinGW (statically linked, but I don't know if that matters).  I needed to make a few adjustments to the CMakeLists.txt file to get it to work.  Here's the diff:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index eaf339b..4838ef5 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -19,7 +19,7 @@ cmake_minimum_required(VERSION 3.5)
 project(ulfius C)
 
 set(CMAKE_C_STANDARD 99)
-set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Werror")
+set(CMAKE_C_FLAGS "-Wall -Werror ${CMAKE_C_FLAGS}")
 
 # library info
 
@@ -214,6 +214,7 @@ if (SEARCH_ORCANIA_U)
         set(LIBS ${LIBS} ${ORCANIA_LIBRARIES})
         include_directories(${ORCANIA_INCLUDE_DIRS})
     endif ()
+    target_link_libraries(ulfius ${LIBS} ${ORCANIA_LIBRARIES})
 endif ()
 
 option(WITH_YDER "Use Yder library to log messages" ON)
```

The first change is because there are two sets of type warnings that occur with some curl functions - using MinGW targeting Windows (it's different between 32-bit and 64-bit builds).  With the "-Werror" flag where it was, there was no way to override it externally, and it caused the build to fail.  It would be best to correct the problems, but some of them were in libmicrohttpd functions and it would get messy.  This thread gets into it a bit:

https://curl.haxx.se/mail/lib-2014-11/0348.html

The second change was necessary for Windows builds, but I don't exactly understand why it isn't needed for CMake builds in Linux.  I'm no CMake expert, but it's consistent with the rest of libraries that are included.

I can provide more information on how I'm building things or the error messages I'm seeing, if wanted (it might be somewhat cluttered).  But hopefully the changes just make sense.

Thank you.

**Comment by babelouest** [comment] 2019-04-12 12:59
Hello @iwagner23 ,

Thanks for the patch!

The first change isn't obvious but I trust your judgement. Sometimes the order of compiler flags are important, but not intuitive.

The second change is an error on my side. I simply forgot it. Why it works on linux may not be linux-related, but because of the yder block up:
https://github.com/babelouest/ulfius/blob/master/CMakeLists.txt#L238

Anyway, I'll apply the changes and let you know, thanks!

**Comment by babelouest** [comment] 2019-04-12 23:42
I've updated the development branch [2.6](https://github.com/babelouest/ulfius/commit/0dfd63982577706290f4c5ef8df22619980dda81) and the LT branch [2.5](https://github.com/babelouest/ulfius/commit/35b162ebc459ea256534f48ba27807ef5985e909) with the changes.

Can you check the new commit (whatever branch you prefer) and let me know if the problem is solved?

**Comment by iwagner23** [comment] 2019-04-14 03:15
Everything is working.  Thank you very much!

**Comment by babelouest** [comment] 2019-04-14 16:53
I'm closing the issue then. Feel free to open a new one if you need to, thanks!

**Closed by babelouest** 2019-04-14 16:53 UTC
Labels: bug
