### ISSUE TITLE
Segmentfault with u_map

### ISSUE THREAD

**Issue by marcohabeck** [babelouest/ulfius#101] opened 2019-02-07 16:33 UTC
when using the functions with u_map in callback with u_request -> seqmentfault.
example Code see Demo..

initialize a struct _u_map self it works

**Comment by babelouest** [comment] 2019-02-07 16:49
Can you be a little more specific?

What example code are you using?

Did you make a change in the code to get the segfault?

**Comment by marcohabeck** [comment] 2019-02-07 17:51
`/**
 * Callback function that put "Hello World!" and all the data sent by the client in the response as string (http method, url, params, cookies, headers, post, json, and user specific data in the response
 */
int callback (const struct _u_request * request, struct _u_response * response, void * user_data) {
  char * url_params = print_map(request->map_url), * headers = print_map(request->map_header), * cookies = print_map(request->map_cookie), 
        * post_params = print_map(request->map_post_body);
.......
  return U_CALLBACK_CONTINUE;
}`

as soon as the first function calls the pointer request -> seqmentfault

**Comment by babelouest** [comment] 2019-02-07 17:57
If you use a specific example program, can you tell me which one?

If not, can you post a sample code that would make me able to reproduce your bug?

Also, what system are you using ulfius on?

**Comment by marcohabeck** [comment] 2019-02-07 18:00
`void test(void){
struct _u_map map;
char * print = NULL;
u_map_put(&map, "key1", "value1");
u_map_put(&map, "key2", "value2");
u_map_put(&map, "key3", "value3");
print = print_map(&map);
o_free(print);
}
`
no problem...

**Comment by babelouest** [comment] 2019-02-07 18:01
Can you answer my questions please?

**Comment by marcohabeck** [comment] 2019-02-07 18:04
No, I tried to integrate it into my program. Then I tried the example. The probolem only occurs in the callback. Also with her examples

**Comment by marcohabeck** [comment] 2019-02-07 18:05
https://github.com/babelouest/ulfius/blob/master/example_programs/request_example/server.c

**Comment by marcohabeck** [comment] 2019-02-07 18:07
see in the callback, the pointer response->map_xxx ist not valid. if you access this on the seqmentfault...

**Comment by marcohabeck** [comment] 2019-02-07 18:09
Forgot to set to zero if there is no data?

**Comment by babelouest** [comment] 2019-02-07 18:25
If you use a `struct _u_map` by yourself, you must initialize it before puttong or getting data, see the [API documentation](https://github.com/babelouest/ulfius/blob/master/API.md#struct-_u_map-api) about it.

If you use a `struct _u_map` within a callback function that is executed via ulfius, you don't have to initialize any data present in the `struct _u_request` or `struct _u_response` you have access to, as stated in the [documentation](https://github.com/babelouest/ulfius/blob/master/API.md#callback-functions-management) as well.

How you manage to get a segmentation fault, I still have no idea because I'm missing a lot of information here, the `request_example` programs server and client work fine on my side. So if you can help me reproducing your error, I might be able to help you.

**Comment by marcohabeck** [comment] 2019-02-07 18:46
yes, I have to use this in my callback. I am using an old ubuntu version and will replace it. Then we'll see if the problem still exists.

**Comment by marcohabeck** [comment] 2019-02-10 14:52
The problem occurs if you include the callback function externally and then access the u_map pointer.

**Comment by marcohabeck** [comment] 2019-02-10 15:17
> [16:13:57] DEBUG: send AEM command to->0x50c2fffed4332b  SequenceId:0x002e command_type:GET_CONTROL
[16:13:57] DEBUG: receive AEM from->0x50c2fffed4332b   sequenceId:0x002e  status:SUCCESS
[16:13:58] DEBUG: IPC request subtype:AECP
[16:13:58] DEBUG: send AEM command to->0x50c2fffed4332b  SequenceId:0x002f command_type:GET_CONTROL
[16:13:58] DEBUG: receive AEM from->0x50c2fffed4332b   sequenceId:0x002f  status:SUCCESS
pointer from map->0x4c000a1000000000
[16:13:59] ALERT: closing App -> Segmentation fault
Fatal error in GNU libmicrohttpd daemon.c:4422: Failed to join a thread
Abgebrochen (Speicherabzug geschrieben)

from URL localhost:7778/avb/00-50-C2-FF-FE-D4-33-2B/discovery

**Comment by marcohabeck** [comment] 2019-02-10 15:24
[16:22:47] DEBUG: receive AEM from->0x50c2fffed4332b   sequenceId:0x0032  status:SUCCESS
######################################################
###################### Callback ######################
######################################################
Method is GET
  url is /avb/00-50-C2-FF-FE-D4-33-2B/discovery

  parameters from the url are
(null)

  cookies are 
key is cook, value is ie


  headers are 
key is Host, value is localhost:7778
key is User-Agent, value is Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
key is Accept, value is text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
key is Accept-Language, value is de,en-US;q=0.7,en;q=0.3
key is Accept-Encoding, value is gzip, deflate
key is DNT, value is 1
key is Connection, value is keep-alive
key is Cookie, value is cook=ie
key is Upgrade-Insecure-Requests, value is 1
key is Cache-Control, value is max-age=0


  post parameters are 
(null)

  raw body is 


  user data is (null)


callback include static ..

**Comment by babelouest** [comment] 2019-02-10 16:01
I still have no idea on how to reproduce your bug.

Please send some sample code that compiles and shows your problem

**Comment by marcohabeck** [comment] 2019-02-10 16:30
The code is very complex. It is an Audio Video Bridging (AVB)  controller. The REST connection is currently running on a fastCGI via unix socket. This is not portable, so I wanted to rebuild the interface on microhttpd ..

I can send you a private link?

**Comment by babelouest** [comment] 2019-02-10 16:53
Don't bother sending me a private link, but tell me if you use ulfius the way it's supposed to be with a `struct _u_instance` initialized, the callback functions added to the instance, then the instance executed and listening on the specified port?

**Comment by marcohabeck** [comment] 2019-02-10 17:07
https://www.sugarsync.com/pf/D290528_08979289_719576 <https://www.sugarsync.com/pf/D290528_08979289_719576>

Hello here is the link… many thanks for the help

Mag Marco

**Comment by marcohabeck** [comment] 2019-02-10 17:14
The lighthttpd is a seprater thread on port 80. AVB is layer 2 ..

**Comment by marcohabeck** [comment] 2019-02-11 11:41
it is a Data structure alignment problem in the struture _u_map.

#pragma pack (1)
struct _u_map {
  int      nb_values;
  char  ** keys;
  char  ** values;
  size_t * lengths;
};

It solves the problem ugly...
The struture _u_map then organizes different in memory and leads to pointers wrong.

**Comment by babelouest** [comment] 2019-02-11 12:56
There's no reason why changing the data order would fix your problem

**Comment by babelouest** [comment] 2019-02-23 13:25
@marcohabeck , any update this?
Were you able to fix your problem?

**Comment by marcohabeck** [comment] 2019-02-23 14:44
No, I do not use your project anymore. I have examined my program with valgrid and some have revised. But they did not have the part to those who called their project.

I now use the libmicrophttpd directly ..

**Comment by marcohabeck** [comment] 2019-02-23 14:51
Her project had proved to be unusable. The library janson needed for my answer 65MB memory! Before I use 1k. The problem is the serial creation of Json ..

**Comment by babelouest** [comment] 2019-02-23 15:04
No problem, I close the issue then

**Closed by babelouest** 2019-02-23 15:04 UTC
Labels: can't reproduce, need info
