### ISSUE TITLE
request->map_post_body mangled on multi-segment request

### ISSUE THREAD

**Issue by ltzoke** [babelouest/ulfius#222] opened 2022-04-01 16:31 UTC
**map_post_body data mangled**
map_post_body JSON content gets mangled occasionally, this seems to happen whenever there is a multi-segment requests. However the JSON part of binary_body is correct.

Also, the second element named 'thumb' is not listed in map_post_body keys (secondary).

**System:**
 - OS/Environment Debian sid
 - Ulfius Version 2.7.7
 - Source installation deb package (libulfius-dev, libulfius2.7 - version 2.7.7-1)

**Data**
diff after line breaks have been added... The broken parts seem to line up with the tcp segments.
```<natasha:issue>$ diff -u map_post_body-payload-pp.json binary_body-pp.json 
--- map_post_body-payload-pp.json	2022-04-01 18:00:48.451784819 +0200
+++ binary_body-pp.json	2022-04-01 17:59:13.990802358 +0200
@@ -42,10 +42,7 @@
 		"addedAt":1648555093,
 		"updatedAt":1648752898,
 		"audienceRatingImage" : "rottentomatoes://image.rating.upright",
-		"chapterSource" : "m"mming.upright",
-		"chapterSource" : "mmtoes://image.rating.upright",
-		"chapterSource" : "m"m//image.rating.upright",
-		"chapterSource" : "m" : "media",
+		"chapterSource" : "media",
 		"primaryExtraKey" : "/library/metadata/126246",
 		"ratingImage" : "rottentomatoes://image.rating.ripe",
 		"Genre":[
@@ -376,7 +373,7 @@
 			{
 				"id":247914,
 				"filter" : "actor=247914",
-				"tag"tag" : "Adam Garcia",
+				"tag" : "Adam Garcia",
 				"count":4,
 				"role" : "Syd",
 				"thumb" : "https://metadata-static.plex.tv/people/5d77682ca091de001f2e6e1b.jpg"
```
Callback function
```
int callback_plex(const struct _u_request *request, struct _u_response *response, void *user_data) {
  json_error_t json_error;
  json_t *payload = json_loads(u_map_get(request->map_post_body, "payload"), 0, &json_error);                                                 
  
  if(!payload) {
    fprintf(stderr, "JSON error: %s\n", json_error.text);
    printf("-----\n%s\n-----\n", print_map(request->map_header));
    printf("-----\n%s\n-----\n", print_map(request->map_post_body));
    truncate("binary_body.raw", 0); // Don't bother with errors for truncate
    truncate("map_post_body-payload.json", 0);
    // Write map_post_body payload to file
    FILE *payloadfd = fopen("map_post_body-payload.json", "w"); // This should be a JSON
    if(!payloadfd) {
      perror("fopen");
    } else {
      fwrite(u_map_get(request->map_post_body, "payload"), u_map_get_length(request->map_post_body, "payload"), 1, payloadfd);
      fclose(payloadfd);
    }
    // Write binary body to file
    FILE *dump = fopen("binary_body.raw", "w");
    if(!dump) {
      perror("fopen");
    } else {
      fwrite(request->binary_body, request->binary_body_length - 1, 1, dump);
      fclose(dump);
    }
    return(U_CALLBACK_CONTINUE);
  }  
  return(U_CALLBACK_CONTINUE);
} 
```

stdout from application
```
JSON error: '}' expected near 'mming'
-----
key is Host, length is 27, value is natasha.lan.valkyr.se:8008
key is User-Agent, length is 38, value is PlexMediaServer/1.25.9.5673-bf5697c5d
key is Accept, length is 4, value is */*
key is Accept-Encoding, length is 5, value is gzip
key is Content-Length, length is 6, value is 16066
key is Content-Type, length is 71, value is multipart/form-data; boundary=------------------------3c4ef43e2a814ce0
-----
-----
key is payload, length is 7621, value is {"event":"media.play","user":true,"owner":true,"Account":{"id":1,"thumb":"https://plex.tv/users/3cf7ca9b4448cb6d/avatar?c=1632916807","title":"zoke"},"Server":{"title":"claire","uuid":"f8bd6ab6f6710ba04ff49d01d6188a3bf66c15c0"},"Player":{"local":true,"publicAddress":"185.130.167.145","title":"Firefox","uuid":"9d63q3g4qc9jsh4htht47swu"},"Metadata":{"librarySectionType":"movie","ratingKey":"126245","key":"/library/metadata/126245","guid":"plex://movie/5d776f09594b2b001e735b26","studio":"Scott Free Productions","type":"movie","title":"Death on the Nile","librarySectionTitle":"Movies","librarySectionID":2,"librarySectionKey":"/library/sections/2","contentRating":"PG-13","summary":"Belgian sleuth Hercule Poirot boards a glamorous river steamer with enough champagne to fill the Nile. But his Egyptian vacation turns into a thrilling search for a murderer when a picture-perfect couple’s idyllic honeymoon is tragically cut short.","rating":6.3,"audienceRating":8.2,"skipCount":15,"year":2022,"tagline":"Murder was just the beginning.","thumb":"/library/metadata/126245/thumb/1648752898","art":"/library/metadata/126245/art/1648752898","duration":7620000,"originallyAvailableAt":"2022-02-11","addedAt":1648555093,"updatedAt":1648752898,"audienceRatingImage":"rottentomatoes://image.rating.upright","chapterSource":"m"mming.upright","chapterSource":"mmtoes://image.rating.upright","chapterSource":"m"m//image.rating.upright","chapterSource":"m":"media","primaryExtraKey":"/library/metadata/126246","ratingImage":"rottentomatoes://image.rating.ripe","Genre":[{"id":18,"filter":"genre=18","tag":"Crime","count":1752},{"id":19,"filter":"genre=19","tag":"Drama","count":3736},{"id":20,"filter":"genre=20","tag":"Mystery","count":1196},{"id":426,"filter":"genre=426","tag":"Thriller","count":3451}],"Director":[{"id":210749,"filter":"director=210749","tag":"Kenneth Branagh","count":10}],"Writer":[{"id":248899,"filter":"writer=248899","tag":"Agatha Christie","count":7},{"id":210104,"filter":"writer=210104","tag":"Michael Green","count":7}],"Producer":[{"id":205367,"filter":"producer=205367","tag":"Ridley Scott","count":33},{"id":210773,"filter":"producer=210773","tag":"Kenneth Branagh","count":6},{"id":201743,"filter":"producer=201743","tag":"Judy Hofflund","count":6},{"id":210913,"filter":"producer=210913","tag":"Kevin J. Walsh","count":8}],"Country":[{"id":3373,"filter":"country=3373","tag":"United Kingdom","count":1183},{"id":166120,"filter":"country=166120","tag":"United States of America","count":5962}],"Guid":[{"id":"imdb://tt7657566"},{"id":"tmdb://505026"},{"id":"tvdb://46622"}],"Rating":[{"image":"imdb://image.rating","value":6.6,"type":"audience","count":5926},{"image":"rottentomatoes://image.rating.upright","value":8.2,"type":"audience","count":2622},{"image":"rottentomatoes://image.rating.ripe","value":6.3,"type":"critic","count":2535},{"image":"themoviedb://image.rating","value":6.6,"type":"audience","count":5919}],"Role":[{"id":210751,"filter":"actor=210751","tag":"Kenneth Branagh","count":19,"role":"Hercule Poirot","thumb":"https://metadata-static.plex.tv/people/5d7768278718ba001e311e43.jpg"},{"id":223086,"filter":"actor=223086","tag":"Gal Gadot","count":16,"role":"Linnet Ridgeway","thumb":"https://metadata-static.plex.tv/7/people/7b272b767dc5e972a1ed2d93822cfd97.jpg"},{"id":240115,"filter":"actor=240115","tag":"Armie Hammer","count":12,"role":"Simon Doyle","thumb":"https://metadata-static.plex.tv/1/people/130667c8bb86bae194bae74fc61ca321.jpg"},{"id":245101,"filter":"actor=245101","tag":"Tom Bateman","count":3,"role":"Bouc","thumb":"https://metadata-static.plex.tv/people/5d776a20fb0d55001f53b0b1.jpg"},{"id":199404,"filter":"actor=199404","tag":"Letitia Wright","count":7,"role":"Rosalie Otterbourne","thumb":"https://metadata-static.plex.tv/9/people/95bd7f16f95577ccfae11f60e4995edb.jpg"},{"id":198851,"filter":"actor=198851","tag":"Sophie Okonedo","count":9,"role":"Salome Otterbourne","thumb":"https://metadata-static.plex.tv/c/people/cb9095ded2836102795711396f50b7db.jpg"},{"id":247297,"filter":"actor=247297","tag":"Jennifer Saunders","count":7,"role":"Marie Van Schuyler","thumb":"https://metadata-static.plex.tv/0/people/05aa10552a6b78878b362b2dc7002fd6.jpg"},{"id":217315,"filter":"actor=217315","tag":"Russell Brand","count":10,"role":"Linus Windlesham","thumb":"https://metadata-static.plex.tv/4/people/48776213afe9712e478cd12a33a3071c.jpg"},{"id":397064,"filter":"actor=397064","tag":"Emma Mackey","role":"Jacqueline de Bellefort","thumb":"https://metadata-static.plex.tv/3/people/37165ea1c8dd351fa8b315d9ae7276ed.jpg"},{"id":203137,"filter":"actor=203137","tag":"Annette Bening","count":14,"role":"Euphemia Bouc","thumb":"https://metadata-static.plex.tv/b/people/b8e357af35e5b5cf0a611380d094075f.jpg"},{"id":243157,"filter":"actor=243157","tag":"Dawn French","count":4,"role":"Mrs Bowers","thumb":"https://metadata-static.plex.tv/e/people/ec3eea7142fa9c14c191f2a9229c29af.jpg"},{"id":295932,"filter":"actor=295932","tag":"Rose Leslie","count":4,"role":"Louise Bourget","thumb":"https://metadata-static.plex.tv/5/people/5776de81aa9b14b914113035ec8da40a.jpg"},{"id":269886,"filter":"actor=269886","tag":"Ali Fazal","count":3,"role":"Katchadourian","thumb":"https://metadata-static.plex.tv/people/5d7768b3308bca00203304c5.jpg"},{"id":230013,"filter":"actor=230013","tag":"John Wolfe","count":3,"role":"Passenger","thumb":"https://metadata-static.plex.tv/f/people/fd0384b9662846c8a525d8ef9a4f775a.jpg"},{"id":397067,"filter":"actor=397067","tag":"Victor Alli","role":"Marc Yves"},{"id":205487,"filter":"actor=205487","tag":"Michael Rouse","count":4,"role":"Private Laurin","thumb":"https://metadata-static.plex.tv/people/5d7768348718ba001e314289.jpg"},{"id":212180,"filter":"actor=212180","tag":"Alaa Safi","count":6,"role":"Corporal","thumb":"https://metadata-static.plex.tv/people/5d77683c103a2d001f5695a8.jpg"},{"id":268786,"filter":"actor=268786","tag":"Orlando Seale","count":5,"role":"Captain Rens","thumb":"https://metadata-static.plex.tv/e/people/eeb061296543c2b678362ff341653a99.jpg"},{"id":296702,"filter":"actor=296702","tag":"Charlie Anson","count":2,"role":"Sergeant Verhaeren","thumb":"https://metadata-static.plex.tv/people/5d776839eb5d26001f1e1a30.jpg"},{"id":397509,"filter":"actor=397509","tag":"Danny Hughes","role":"Soldier 1"},{"id":397510,"filter":"actor=397510","tag":"Sam James Page","role":"Soldier 2"},{"id":381335,"filter":"actor=381335","tag":"James Schofield","count":2,"role":"German Soldier 1","thumb":"https://metadata-static.plex.tv/7/people/7212e2115d2e7c2dd5df139777a44254.jpg"},{"id":397066,"filter":"actor=397066","tag":"George Jaques","role":"German Soldier 2","thumb":"https://metadata-static.plex.tv/c/people/cd545744c512b7c7f88a099273aa7f36.jpg"},{"id":255700,"filter":"actor=255700","tag":"Jonah Rzeskiewicz","count":2,"role":"German Soldier 3","thumb":"https://metadata-static.plex.tv/b/people/bb8ef6d0e17f4851bbfefec83f8fe3de.jpg"},{"id":210759,"filter":"actor=210759","tag":"Eleanor de Rohan","count":2,"role":"Nurse"},{"id":198902,"filter":"actor=198902","tag":"Susannah Fielding","count":2,"role":"Katherine","thumb":"https://metadata-static.plex.tv/d/people/d487edcb7629136c96e13b5ff1f2a03b.jpg"},{"id":247914,"filter":"actor=247914","tag"tag":"Adam Garcia","count":4,"role":"Syd","thumb":"https://metadata-static.plex.tv/people/5d77682ca091de001f2e6e1b.jpg"},{"id":397065,"filter":"actor=397065","tag":"Rick Warden","role":"Monsieur Blondin"},{"id":397511,"filter":"actor=397511","tag":"Noel White","role":"Maître 'D Chez Ma Tente","thumb":"https://metadata-static.plex.tv/people/5f62573e912efa00413d0a08.jpg"}]}}
-----
```
Attaching files written by application as well as pcap-dump.
[foo.zip](https://github.com/babelouest/ulfius/files/8399433/foo.zip)

**Comment by babelouest** [comment] 2022-04-01 19:11
Hello @ltzoke ,

I think I'm missing some context here to understand your question.

For starters, can you post a source code sample I can compile as is, and the steps to reproduce your issue?

Also, if I read the attached code, I don't understand what you're trying to achieve:
- you directly parse the `request->binary_body` as JSON, where you should use instead [ulfius_get_json_body_request](https://github.com/babelouest/ulfius/blob/master/API.md#use-json-in-request-and-response-body-)
- the file map_post_body-payload-pp.json isn't in JSON format, and I don't understand what is its purpose

Can you enlighten me?

**Comment by ltzoke** [comment] 2022-04-01 21:33
Hi,

I'm trying to parse data sent by a plex mediaserver. It sends data using `Content-Type: multipart/form-data` which makes `ulfius_get_json_body_request` fail with a message that it expects `Content-Type: application/json`. The request always contains a JSON tagged with the name 'payload', and may for some events contain an additional element which is a jpeg-image, this image is tagged as 'thumb'.

I had some issues with libulfius occasionally not getting a valid JSON when using `u_map_get(request->map_post_body, "payload")` (as seen in map_post_body-pp.json). The callback function listed above was only written to try to find out what was going wrong.

My conclusion was that when the request is split over multiple tcp-segments the JSON stored in the 'payload' key in `request->map_post_body` has extra characters introduced in the areas where the segments are put together.

Since the content of 'payload' in `request->map_post_body` differs from the corresponding part in `request->binary_body` it seems to me that something is going wrong when the data is added to `request->map_post_body`. See the diff from my previous post to see the extra characters introduced in `request->map_post_body`.

**Comment by ltzoke** [comment] 2022-04-01 23:27
To clarify, the file `map_post_body-payload-pp.json` is just a copy of `map_post_body-payload.json` with line breaks added. This is to make it easier to see the difference between the JSON in `request->map_post_body` and `request->binary_body`. The JSON from `request->binary_body` with the same line breaks are saved as `binary_body-pp.json`.

This was done in order to be able to use the `diff` command to see what's wrong.

**Comment by babelouest** [comment] 2022-04-02 14:47
Hello @ltzoke ,

I think I found the cause of the problem, it should be fixed in the master branch. Can you test with the last commit?

**Closed** 2022-04-02 14:46 UTC
Labels: need info

**Comment by ltzoke** [comment] 2022-04-03 14:39
I have done some testing and it's been working as expected so far.

Good job, and thanks for an awesome library.
