### ISSUE TITLE
Send json as string data over websocket.

### ISSUE THREAD

**Issue by bdnsoft** [babelouest/ulfius#121] opened 2019-05-31 12:00 UTC
Hi,

I am triyng to send json data over websocket and after a little time chrome say "failed: Invalid frame header" or "not valid UTF8".

This is my litllet example code:

//Pack json
                        json_t * str_json = json_pack("{ssss}","id","data","message","xxxxxxx");

//conver string data: I tried JSON_COMPACT,JSON_ENSURE_ASCII... 
                        char * str_data = json_dumps(str_json, JSON_ENCODE_ANY);

//send
                        ret = ulfius_websocket_send_message(websocket_manager, 
                                  U_WEBSOCKET_OPCODE_TEXT, o_strlen(str_data), str_data);

I tried send only a string (not as json format) it works perfect but if i send as json, i have this problems.

Do you know what happen?

Thanks for advise.

**Comment by babelouest** [comment] 2019-05-31 13:51
Hello @bdnsoft ,

Can you give me more information about your issue?
Sending JSON over a websocket is possible because I do it in [Taliesin](https://github.com/babelouest/taliesin/blob/master/src/webservice.c#L1456) for example.
Your problem might come from various places. Browsers have difficulties with fragmented messages but since you use `ulfius_websocket_send_message` that's not the case. Have you checked the result of `ulfius_websocket_send_message`? It should be `U_OK`.
Also, you can enable `yder` logs, that may give you more information.

You can try to send a simple text string and a raw JSON string, something like:

```C
char * message_str = "Hello World!", * message_json = "{\"message\":\"Hello World!\"}";

if (ulfius_websocket_send_message(websocket_manager,
U_WEBSOCKET_OPCODE_TEXT, o_strlen(message_str), message_str) != U_OK) {
  printf("Error sending message_str\n");
}

if (ulfius_websocket_send_message(websocket_manager,
U_WEBSOCKET_OPCODE_TEXT, o_strlen(message_json), message_json) != U_OK) {
  printf("Error sending message_json\n");
}
```

If none of this work, can you post a sample code to reproduce the bug and more information on the chrome error (how do you get this error, etc.)

**Comment by bdnsoft** [comment] 2019-06-03 10:44
Thanks for your answer.

I woult like to explain what is happaning.

First, I know ulfius it's working ok. I send some messages over websocket and it works ok but I don't why when I send it in json fomat ,after some messages sent, it doesn't work.

My app is sending messages that read from file, line by line, and if I send this line as text format (not json) it works ok but in json format no. 

and yes I'm checking value returned ulfius_websocket_send_message() and it is ok.

I attach "log file example". Read it line by line and send it:

![chrome_error](https://user-images.githubusercontent.com/5072286/58796220-00e8fd00-85fd-11e9-8cbb-cbdfe66e1bbd.jpg)

{"id":"realtimelog","message":"2019-06-03 12:25:59.022 [DEBUG] PowerManager. Reinicia peticiones de potencia"}

Inside message tag is the line what i read in file.

[log_app.log](https://github.com/babelouest/ulfius/files/3247113/log_app.log)


![chrome_error1](https://user-images.githubusercontent.com/5072286/58796274-2249e900-85fd-11e9-8cd4-2b5c398245ff.jpg)

Thanks a lot.

**Comment by babelouest** [comment] 2019-06-03 13:04
I'm still not entirely sure but if you [search for your error message](https://duckduckgo.com/?q=%22could+not+decode+a+text+frame+as+utf-8%22&ia=web) on the web, you get similar issues concerning websockets (mostly) with Chrome (often).

I will give you more cues, let me know the results.

First, have you tried with firefox instead of chrome? Does it change something?

It may also come from memory errors. By design, all sent and received messages are kept in the websocket manager, so after use, you can clear a message you just sent or received.
It will be something like that:

```C
// Clear the last sent message
last_message = ulfius_websocket_pop_first_message(websocket_manager->message_list_outcoming);
if (last_message != NULL) {
  ulfius_clear_websocket_message(last_message);
}

// Clear the last received message
last_message = ulfius_websocket_pop_first_message(websocket_manager->message_list_incoming);
if (last_message != NULL) {
  ulfius_clear_websocket_message(last_message);
}
```

Also, when you send websocket messages, is it in a single thread or in multiple threads? `ulfius_websocket_send_message` is thread-safe but you might have found a bug.

**Comment by bdnsoft** [comment] 2019-06-03 14:57
Sorry but It didn't work.

I tried with firefox, IE and Chrome and after short time receiving messages it fails.  

But the strangest thing that I do not understand is sending messages, no as json, it works perfect. 

One more thing I open Firefox and connect and open Chrome and connect, after receiving some messages it fails both at the same time.

about your last questions i don't sure about exactly what do you want to know but :

This is the call:

ulfius_add_endpoint_by_val(config->instance, "GET", PREFIX_WEBSOCKET, "/realtimelog/", 2, &callback_websocket_log_real_time, (void*) config);  

Every connection create a new instance where, we receive and send message.

**Comment by bdnsoft** [comment] 2019-06-03 15:05
I attached a different error:
"failed: Invalid frame header"

Maybe it helps to you. It is showed sometimes and sometimes show UTF8 error.

![chrome_error2](https://user-images.githubusercontent.com/5072286/58812087-62bb5e00-8621-11e9-835f-b67e1279f7c3.jpg)

**Comment by babelouest** [comment] 2019-06-03 15:18
At least it looks like not a browser issue.

Indeed, every websocket connection has its own context in Ulfius. More precisely, you have two message queues: `websocket_manager->message_list_outcoming` and `websocket_manager->message_list_incoming`, which store sent messages and received messages.

In your case, the websockets seems to only send messages to the client, but lots of them, and you don't have to keep them in the message queue after they've been sent, so you can easily clean the message queue after each message:

```C
// str_json is your json message
char * str_data = json_dumps(str_json, JSON_COMPACT);

// Send websocket message
if (str_data != NULL && ulfius_websocket_send_message(websocket_manager, U_WEBSOCKET_OPCODE_TEXT, o_strlen(str_data), str_data) == U_OK) {
  // Get the last message sent (the one above)
  struct _websocket_message * last_message = ulfius_websocket_pop_first_message(websocket_manager->message_list_outcoming);
  if (last_message != NULL) {
    // Cleanup the last message sent from memory
    ulfius_clear_websocket_message(last_message);
  }
}

// Cleanup str_data
free(str_data);
```

You can also try to use `uwsc` but only if you're curious, I guess it will have about the same result.

```shell
$ uwsc ws://secureboard2/websocket/realtimelog?jwt=<your_jwt>
```

A few more questions:
- About how many messages are sent to the client before the error appears?
- What is roughly the frequency of the messages sent per seconds or minute?
- Does the error appears always on the same message?

**Comment by bdnsoft** [comment] 2019-06-03 18:08
Yes, I tried deleting last message after send it but it didn't work.

I have just tried your program "uwsc" and the answer is this:

>>>>>>

Server message: '{"id":"realtimelog","message":"2019-06-03 19:59:27.005 [DEBUG] [COREDBIF] Delay expired after color change. Requesting instant values"}'

Server message: '{"id":"realtimelog","message":"2019-06-03 19:59:27.006 [DEBUG] Pedir potencia de: G1R"}'

Server message: '{"id":"realtimelog","message":"2019-06-03 19:59:27.007 [DEBUG] Pide potencia de G1R a M2: tarj 1, grupo 1, color 0"}'

Server message: '▒fid":"realtimelog","message":"2019-06-03 19:59:27.025 [DEBUG] [M2] Board 1, channel 1, power 1476 (dW), max power: 1476 (dW)n '

Server message: 'id":"realtimelog","message":"2019--03 19:59:27.026 [DEBUG] Respuesta de M2 Val Instant d▒~'

Server message: '{"id":"realtimelog","message":"2019-06-03 19:59:27.892 [DEBUG] [COLORES] SubR:0 EN FASE"}'

Server message: '{"id":"realtimelog","message":"2019-06-03 19:59:27.893 [DEBUG] V2X: Fase actual 2, siguiente fase 3"}'

Server message: '{"id":"realtimelog","message":"2019-06-03 19:59:27.895 [DEBUG] V2X: De fase 2 a fase 3: Transicion 2, primera posicion 2"}'

>>>>>>


You can see message number 4 and 5 they aren't a good json format, the next messages they are ok again.

What do you thing about this? 

Thanks.

**Comment by babelouest** [comment] 2019-06-03 18:42
Then let's go deeper in the debugging messages then.

If you use the kind of following code:

```C
// str_json is your json message
char * str_data = json_dumps(str_json, JSON_COMPACT);

// Send websocket message
if (str_data != NULL && ulfius_websocket_send_message(websocket_manager, U_WEBSOCKET_OPCODE_TEXT, o_strlen(str_data), str_data) == U_OK) {
  printf("Message generated (%zu bytes): '%.*s'\n", strlen(str_data), strlen(str_data), str_data);
  // Get the last message sent (the one above)
  struct _websocket_message * last_message = ulfius_websocket_pop_first_message(websocket_manager->message_list_outcoming);
  if (last_message != NULL) {
    printf("Message stored (%zu bytes): '%.*s'\n", last_message->data_len, last_message->data_len, last_message->data);
    // Cleanup the last message sent from memory
    ulfius_clear_websocket_message(last_message);
  }
}

// Cleanup str_data
free(str_data);
```

Are the debug messages correct or are they invalid JSON too?
More importantly, are the data in `Message generated` and `Message stored` exactly the same?

If all the debug messages are always correct and some the messages received by the client are invalid, then it may comes from elsewhere than the message generation in Ulfius, perhaps the network.

Are the server and the client the same device?
What kind of OS is running your application using Ulfius?

Also, can you answer my 3 last quesitons from my previous post?

**Comment by bdnsoft** [comment] 2019-06-03 19:18
1.Are the debug messages correct or are they invalid JSON too? They are correct.

2.More importantly, are the data in Message generated and Message stored exactly the same? They are the same

3.Are the server and the client the same device? When test your app uwsc they are in the same device when try with chrome or firefox no.

4.What kind of OS is running your application using Ulfius? This an embedded linux system YOCTO.

Previous questions:

5.About how many messages are sent to the client before the error appears? It is aleatory, sometimes is over 20 messages sometimes is more messages.

6.What is roughly the frequency of the messages sent per seconds or minute? Maybe 9 or 10 messages per second. But no problem if i send them whitout json format.  If i send only line i read in file is send ok.

7.Does the error appears always on the same message? No


But I don't think the problem is the network becouse in the same device with uwsc received bad json format.

> Server message: '▒fid":"realtimelog","message":"2019-06-03 19:59:27.025 [DEBUG] [M2] Board 1, channel 1, power 1476 (dW), max power: 1476 (dW)n '
> 
> Server message: 'id":"realtimelog","message":"2019--03 19:59:27.026 [DEBUG] Respuesta de M2 Val Instant d▒~'
> 
>

Maybe the problem is in other place but it is difficult to know where...

**Comment by babelouest** [comment] 2019-06-03 19:45
Thanks for your answers.
So according to the six stages of debugging, I'm at stage 4 :-)

```
1. That can't happen
2. That doesn't happen on my machine
3. That shouldn't happen
4. Why does that happen?
5. Oh, I see
6. How did that ever work?
```

It shouldn't be a performance issue because 9-10 messages per seconds isn't that big, even for an embedded system. Every message sent and stored use about twice the size of the message, one size for `message->data`, one size for the buffer generated out of `message->data` and written to the socket, plus about a constant size for the metadata. Also, after sending the message, the buffer is freed.

And since your messages look like 200 bytes top, that would be like 9kB for a high estimation of how much memory is spent on the messages. And I imagine your device has more than that amount to provide to your application.

I would like to see if something in YOCTO would cause this problem. If the websocket simply reads the log file and sends the new lines to the connected client, can you run this websocket service on a different device with the same modus operandi?

**Comment by bdnsoft** [comment] 2019-06-04 11:56
Hi again,
I tried app in a ubuntu i get the same. I don't know where is the problem :(

How can I active log in ulfius?

I think my solution is check data in front-end when it isn't a correct json format but I don't think it is the best solution.

**Comment by babelouest** [comment] 2019-06-04 13:02
Hello,

If you're able to reproduce the problem with a minimal application, can you post the code here so I will try to reproduce the problem. Can you also post a sample log file to reproduce your environment? Don't forget to anonymize the log file if you don't want private data to be out in the wild.

To activate the logs in Ulfius, you must use `yder` functions. In your `main()` function, initialize yder before running ulfius instance, and close yder after running ulfius instance:

```C
int main() {
  // Initialize yder logs
  y_init_logs("simple_example", Y_LOG_MODE_CONSOLE, Y_LOG_LEVEL_DEBUG, NULL, "Starting simple_example");

  // Run ulfius instance
  ulfius_start_framework(&instance);

  // Wait for close signal and close ulfius instance
  ulfius_stop_framework(&instance);

  // close yder logs
  y_close_logs();
}
```

**Comment by bdnsoft** [comment] 2019-06-04 13:53
Hello,

I detected, thanks a your app uwsc, that more or less there was a message wthat seems was the cause of problem.

This message, is not a correct json format:

> Server message: '▒fid":"realtimelog","message":"2019-06-03 19:59:27.025 [DEBUG] [M2] Board 1, channel 1, power 1476 (dW), max power: 1476 (dW)n '


I have got it works ok doing it:

this message:

>  '{"id":"realtimelog","message":"2019-06-04 15:43:21.069 [DEBUG] [M2] Board 1, channel 4, power 684 (dW), max power: 684 (dW)"}'


trasform to:

>  '{"id":"realtimelog","message":"2019-06-04 15:43:21.069 [DEBUG] [M2] Board 1, channel 4, power 684 dW, max power: 684 dW"}'

I delete "( )" between dW and now it is working ok.

I don't know why but it is working for one hour without any problem.

What do you thing?

And thanks a lot for your help.

**Comment by bdnsoft** [comment] 2019-06-04 14:17
I found other message, This message only appear when device start.


> '▒did":"realtimelog","message":"2019-06-04 16:13:39.297 [DEBUG] Activado el horario de verano. Suma una hora a la hora UTC...'

From:

> '{id":"realtimelog","message":"2019-06-04 16:13:39.297 [DEBUG] Activado el horario de verano. Suma una hora a la hora UTC...}'

to:

> '{id":"realtimelog","message":"2019-06-04 16:13:39.297 [DEBUG] Activado el horario de verano. Suma una hora a la hora UTC}'

I deleted "..." and the end of message and now it is working.

I don't know waht is happening but i suposo that the problem is a combiantion characters with JSON format is interprete wrong, don't you?

**Comment by babelouest** [comment] 2019-06-04 14:52
That's very possible.

How do you parse the log file into JSON? That could be the source of the problem.

**Comment by bdnsoft** [comment] 2019-06-04 15:06
I do it:

str_json = json_pack("{ssss}","id",KEY_PARAM_REAL_TIME_LOG,"message",line_file_logger);

where "line_file_logger" is line of file. I don't do anything special.

**Comment by babelouest** [comment] 2019-06-04 15:11
Can you post a sample log file I could use to reproduce your bug?

**Comment by bdnsoft** [comment] 2019-06-04 15:19
Yes, I can

[log_20190604.zip](https://github.com/babelouest/ulfius/files/3253158/log_20190604.zip)

You can see sentences: 

2019-06-04 01:00:27.409 [DEBUG] Activado el horario de verano. Suma una hora a la hora UTC...
2019-06-04 01:00:28.552 [DEBUG] [M2] Board 1, channel 1, power 1468 (dW), max power: 1468 (dW)

and:

2019-06-04 01:00:27.409 [DEBUG] Activado el horario de verano. Suma una hora a la hora UTC.
2019-06-04 01:00:28.552 [DEBUG] [M2] Board 1, channel 1, power 1468 dW, max power: 1468 dW

The first senteces is where is the problem.

Thanks again.

**Comment by babelouest** [comment] 2019-06-06 16:59
I'm currently at stage 5: `Oh, I see`

The problem isn't from the message contains, but its length. If you send a message of 125 or 128 bytes, it works. If you send a message of  126 or 127 bytes, you have the error.

Technically the problem probably lies between the functions `ulfius_build_frame` and `ulfius_build_message`. I'll find the problem and the fix that goes with it.

**Comment by babelouest** [comment] 2019-06-06 23:55
[Holy guacamole!](https://github.com/babelouest/ulfius/commit/944e82af50890d19230c5e61ffe6c3580f47544b)

This one was sneaky, but it's fixed now :-)
The bug did came from Ulfius and it was there the whole time.

It will be present in the next releases 2.5.5 and 2.6.0, but if you're in a hurry, you can apply the fix yourself. In the file [u_websocket.c](https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c), on line [131](https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L131), replace

```C
} else if (message->data_len > 128) {
```

with

```C
} else if (message->data_len > 125) {
```

Thanks for pointing out @bdnsoft !

**Comment by bdnsoft** [comment] 2019-06-07 06:35
Amazing awesome fantastic !!!  This mistake was very difficult to find it, amazing.

Thank you a lot for your help and thanks for this amazing lib.

**Comment by babelouest** [comment] 2019-06-07 12:35
Thanks!

Do you confirm the bug is fixed on your side?

**Comment by bdnsoft** [comment] 2019-06-09 12:25
Hi Nicolas,
I tried it and it is working perfectly.
I appreciated your support very much.
Thank you very munch,

**Closed** 2019-06-27 23:48 UTC
Labels: bug
